### ISSUE TITLE
Invalid rule schema

### ISSUE THREAD

**Issue by rossbrenner** [elttam/semgrep-rules#5]
**Describe the bug**
Getting an error when trying to run semgrep with elttam rules. 

![image](https://user-images.githubusercontent.com/106716788/180142490-7b7f5dc8-ec5c-4c45-b70b-d9ae90ea1571.png)

**To Reproduce**
`semgrep --config semgrep-rules/rules semgrep-rules/rules/`

**Expected behavior**
Expect to see semgrep findings

**Additional Context**

- semgrep runs successfully with  "p/owasp-top-ten", "p/xss" and "ci"
- elttam rules repo was cloned properly.
- managed to run semgrep with elttam rules successfully in the past on the same environment 
- running semgrep in VScode in wsl ubuntu terminal

**Tag the elttam semgrep maintainer(s)** for extra help?
cc @ben-elttam @matt-elttam

**Comment by ben-elttam** [comment]
Which version of semgrep are you running?

`semgrep --version`: `0.104.0`.

Are you using the latest commit of elttam/semgrep-rules?

`git describe --all --long --dirty`:  `heads/main-0-gc80bd5f`

I cannot reproduce the error.

```
elttam % semgrep --config semgrep-rules/rules semgrep-rules/rules/

Scanning across multiple languages:
    <multilang> | 2 rules × 12 files
           yaml | 2 rules ×  9 files
           java | 4 rules ×  2 files

  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|23/23 tasks

Findings:
<snip>

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.

Ran 8 rules on 12 files: 20 findings.
```

```
elttam/semgrep-rules/rules/java/spring/security/audit/remoting $ semgrep --validate --strict -f UnsafeHttpInvokerServiceExporter.yml
Fetching rules from https://semgrep.dev/registry.
Configuration is valid - found 0 configuration error(s), and 3 rule(s).
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
```

```
elttam/semgrep-rules/rules/java/spring/security/audit/remoting $ semgrep --test --strict
Scanning 1 file.
Scanning 1 file with 3 java rules.
3/3: ✓ All tests passed
No tests for fixes found.
```

**Comment by ben-elttam** [comment]
@rossbrenner I have removed spaces from the rule IDs, in commits 41973de and 59d785d. I think this will fix the issue you were having.

Please let me know if this fixes the issue or not.

**Comment by rossbrenner** [comment]
Worked like a treat. Thanks @ben-elttam
